#28 Proposed changes using `Formatter`
dominikbraun/timetrace pull request #44
Opened 2021-05-19 12:54 UTC by aaronsheah

<img width="593" alt="Screenshot 2021-05-19 at 13 39 06" src="https://user-images.githubusercontent.com/1883562/118814505-22098d80-b8a8-11eb-82da-4aff0e61d039.png">

2021-05-19 20:41 UTC, dominikbraun requested changes
@aligator PTAL

2021-05-19 20:41 UTC, dominikbraun commented on core/formatter.go
> +	default12HoursRecordKeyLayout = "03:04PM"
I think this record key layout should be `2006-01-02-03-04PM`, shouldn't it?

2021-05-19 20:41 UTC, dominikbraun commented on core/formatter.go
> +	return default12HoursRecordKeyLayout
```suggestion
	if f.use12Hours {
		return default12HoursRecordKeyLayout
	}
	return defaultRecordKeyLayout
```

2021-05-19 22:41 UTC, aaronsheah commented
Thanks @dominikbraun silly mistakes, must have still haven't woken up then 😆

2021-05-21 14:27 UTC, dominikbraun commented
@aaronsheah I think you need to use the new Formatter for `get` and `delete` as well - then this PR can be merged 😄

2021-05-21 17:42 UTC, aligator commented
> @aligator PTAL

Looks good to me :-)

2021-05-21 20:42 UTC, aaronsheah commented
@dominikbraun updated :)

2021-05-22 08:35 UTC, dominikbraun approved these changes
LGTM 👍

2021-05-22 17:18 UTC, merged