fixed issue with attempting to load data from an empty directory
dominikbraun/timetrace pull request #96
Opened 2021-05-31 03:59 UTC by joshuaherrera

Resolves issue #95 by checking that the latest directory contains at least 1 file.

2021-06-01 08:38 UTC, dominikbraun requested changes
Nice solution! Maybe we'll extend the `Filesystem` interface later and add a function like `LatestRecordDirPath` so we can move this filesystem-related logic into the `fs` package.

Otherwise, I just have a small suggestion 😄

2021-06-01 08:38 UTC, dominikbraun commented on core/record.go
> +	}
I suggest returning `ErrTrackingNotStarted` to indicate that the user has no start tracking first.

```suggestion
	if err != nil {
		if errors.Is(err, ErrAllDirectoriesEmpty) {
			return nil, ErrTrackingNotStarted
		}
		return nil, err
	}
```

2021-06-01 16:22 UTC, joshuaherrera commented
That change looks good, I just committed our suggestion.

> Maybe we'll extend the `Filesystem` interface later and add a function like `LatestRecordDirPath` so we can move this filesystem-related logic into the `fs` package.

Yes, I wasn't sure where the best place to put these helper functions would be, so I put them in the timetrace.go file. I like this idea better though.

2021-06-01 16:27 UTC, dominikbraun approved these changes
LGTM 👍

2021-06-02 06:51 UTC, merged

2021-06-02 07:41 UTC, dominikbraun commented
This fix is contained in [release 0.7.1](https://github.com/dominikbraun/timetrace/releases/tag/v0.7.1).